# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weathy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weathy
  pod 'Alamofire', '~> 5.2.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
end
